### ISSUE TITLE
A slight misunderstanding regarding the usage of the TCP channel to send player position data.

### ISSUE THREAD

**Issue by beProsto** [wawesomeNOGUI/WebRTCGame#2]
Shouldn't it be the job of the UDP channel? Wasn't that the whole point of doing this with WebRTC?

I'm confused. :c

**Comment by wawesomeNOGUI** [comment]
Hi! Sorry about the confusion, we use the unreliable channel to send updates to the players about things that are moving fast and that you only need the most recent data of (e.g. other player’s movement). In this repository you actually could use the udp channel to send where a client player moved to to the server, but I did it using The TCP channel because instead of the clients just sending what x and y they moved to, to prevent cheating they should just send what buttons they pressed so the server can resolve what that means movement wise, and sending button presses would need reliable transport so the server receives every button pressed.

**Comment by beProsto** [comment]
Thanks for the answer, it makes a lot more sense than what i thought was happening lol.

Anywho, really cool project! It makes it easy to somewhat understand what's going on :D

**Comment by wawesomeNOGUI** [comment]
No problem! Thanks! If you have any more questions feel free to ask!
